# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 20:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20160929_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igpost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
