# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 15:45
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_auto_20160930_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
