# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0010_userprofile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(default=0, related_name='followers_profile', to='feeds.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(default=0, related_name='following_profile', to='feeds.UserProfile'),
        ),
    ]
