# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 18:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0011_auto_20161005_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igpost',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
