# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0013_auto_20161005_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='igpost',
            name='profile',
        ),
    ]
