# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-06 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0014_remove_igpost_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers_profile', to='feeds.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following_profile', to='feeds.UserProfile'),
        ),
    ]
