# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0015_auto_20161006_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='igpost',
            name='user',
        ),
        migrations.AddField(
            model_name='igpost',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feeds.UserProfile'),
        ),
    ]
