# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-09 17:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0019_auto_20161007_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
