# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0028_auto_20161102_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
    ]
